#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(pwd)"
# 兩個已知來源根目錄（可再加）
CANDIDATE_ROOTS=(
  "/home/youjie/projects/smart-mail-agent"
  "/home/youjie/projects/smart-mail-agent_ssotn"
)

# 在多處候選路徑裡選「存在、體積最大、或 mtime 最新」的那一個
pick_best() {
  local pattern="$1"; shift
  local -a found=()
  for r in "${CANDIDATE_ROOTS[@]}"; do
    while IFS= read -r -d '' f; do
      found+=("$f")
    done < <(find "$r" -type f -path "$pattern" -print0 2>/dev/null || true)
  done
  # 也許傳的是具體檔名（非 glob）
  for r in "${CANDIDATE_ROOTS[@]}"; do
    if [[ -f "$r/$pattern" ]]; then
      found+=("$r/$pattern")
    fi
  done
  if ((${#found[@]}==0)); then
    echo ""
    return 0
  fi
  # 依：檔案大小 desc、mtime desc 排序取第一
  printf '%s\0' "${found[@]}" \
  | xargs -0 stat --printf='%s\t%Y\t%n\0' \
  | sort -z -k1,1nr -k2,2nr \
  | head -z -n1 \
  | awk -v RS='\0' -F'\t' '{print $3}'
}

# 幫助函式：輸出 key: path（含 Windows 路徑）
emit_entry() {
  local key="$1"; shift
  local path="$1"; shift
  local wpath=""
  if command -v wslpath >/dev/null 2>&1 && [[ -n "$path" ]]; then
    wpath="$(wslpath -w "$path" 2>/dev/null || true)"
  fi
  jq -n --arg k "$key" --arg p "$path" --arg wp "$wpath" '{key:$k, path:$p, win:$wp}'
}

# 尋找各模組資產/資料
declare -A MAP

# spam 文字模型（prod）
MAP[spam_text_model]="$(pick_best "*/artifacts_prod/text_lr_platt.pkl")"
MAP[spam_model_pipeline]="$(pick_best "*/artifacts_prod/model_pipeline.pkl")"
MAP[spam_ens_thresholds]="$(pick_best "*/artifacts_prod/ens_thresholds.json")"

# spam_sa / spam / trec06c 三套資料（可能同時存在）
MAP[spam_sa_train]="$(pick_best "*/data/spam_sa/train.jsonl")"
MAP[spam_sa_val]="$(pick_best "*/data/spam_sa/val.jsonl")"
MAP[spam_sa_test]="$(pick_best "*/data/spam_sa/test.jsonl")"

MAP[spam_train]="$(pick_best "*/data/spam/train.jsonl")"
MAP[spam_val]="$(pick_best "*/data/spam/val.jsonl")"
MAP[spam_test]="$(pick_best "*/data/spam/test.jsonl")"

MAP[trec_train]="$(pick_best "*/data/trec06c_zip/train.jsonl")"
MAP[trec_val]="$(pick_best "*/data/trec06c_zip/val.jsonl")"
MAP[trec_test]="$(pick_best "*/data/trec06c_zip/test.jsonl")"

# intent 模型/資料
MAP[intent_pro_cal]="$(pick_best "*/artifacts/intent_pro_cal.pkl")"
MAP[intent_svm_base]="$(pick_best "*/artifacts/intent_svm_plus.pkl")"
MAP[intent_data_merged]="$(pick_best "*/data/intent/i_20250901_merged.jsonl")"
MAP[intent_data_full]="$(pick_best "*/data/intent/i_20250901_full.jsonl")"

# KIE 資料與 model_xlmr 目錄（以含 tokenizer.json 的資料夾為準）
MAP[kie_train]="$(pick_best "*/data/kie/train.jsonl")"

# 找含 tokenizer.json 的資料夾，取最「新且大」
best_kie_dir() {
  local -a candidates=()
  for r in "${CANDIDATE_ROOTS[@]}"; do
    while IFS= read -r -d '' tok; do
      candidates+=("$(dirname "$tok")")
    done < <(find "$r" -type f -name tokenizer.json -path "*/model_xlmr/*" -print0 2>/dev/null || true)
  done
  if ((${#candidates[@]}==0)); then
    echo ""
    return 0
  fi
  # 以資料夾內檔案總大小 + mtime 決定
  {
    for d in "${candidates[@]}"; do
      sz=$(du -sb "$d" 2>/dev/null | awk '{print $1}')
      mt=$(stat -c %Y "$d" 2>/dev/null || echo 0)
      printf '%s\t%s\t%s\n' "$sz" "$mt" "$d"
    done
  } | sort -k1,1nr -k2,2nr | head -n1 | awk -F'\t' '{print $3}'
}
MAP[kie_model_dir]="$(best_kie_dir)"

# 產出 paths.json（含 Windows mirrored path）
TMP="$(mktemp)"
{
  echo '{'
  first=1
  for k in "${!MAP[@]}"; do
    p="${MAP[$k]}"
    if [[ -n "$p" && -e "$p" ]]; then
      obj="$(emit_entry "$k" "$p")"
    else
      obj="$(jq -n --arg k "$k" '{key:$k, path:null, win:null}')"
    fi
    if (( first )); then first=0; else echo ','; fi
    echo -n "\"$k\": $(echo "$obj" | jq -c '.')"
  done
  echo '}'
} > "$TMP"

mkdir -p "$ROOT/configs/data_contracts"
jq '.' "$TMP" > "$ROOT/configs/data_contracts/paths.json"

# 建立 models/ 內部 symlink，方便現有程式載入
mkdir -p "$ROOT/models"
while IFS= read -r key; do
  path=$(jq -r --arg k "$key" '.[$k].path // empty' "$ROOT/configs/data_contracts/paths.json")
  [[ -z "$path" ]] && continue
  base="$(basename "$path")"
  ln -sf "$path" "$ROOT/models/${key}__${base}"
done < <(jq -r 'keys[]' "$ROOT/configs/data_contracts/paths.json")

# 產生 .env.local 供程式讀取
cat > "$ROOT/.env.local" <<ENV
# auto-generated by wire_paths.sh
SMA_SPAM_TEXT_MODEL=$(jq -r '.spam_text_model.path // empty' "$ROOT/configs/data_contracts/paths.json")
SMA_SPAM_PIPELINE=$(jq -r '.spam_model_pipeline.path // empty' "$ROOT/configs/data_contracts/paths.json")
SMA_SPAM_THR=$(jq -r '.spam_ens_thresholds.path // empty' "$ROOT/configs/data_contracts/paths.json")
SMA_INTENT_PRO_CAL=$(jq -r '.intent_pro_cal.path // empty' "$ROOT/configs/data_contracts/paths.json")
SMA_INTENT_SVM_BASE=$(jq -r '.intent_svm_base.path // empty' "$ROOT/configs/data_contracts/paths.json")
SMA_INTENT_DATA=$(jq -r '.intent_data_merged.path // empty' "$ROOT/configs/data_contracts/paths.json")
SMA_KIE_DIR=$(jq -r '.kie_model_dir.path // empty' "$ROOT/configs/data_contracts/paths.json")
ENV

# 驗證輸出表
echo -e "\n[SUMMARY] linked assets:"
printf "%-24s | %-6s | %s\n" "KEY" "FOUND" "PATH"
printf -- "-------------------------+--------+---------------------------------------------\n"
for k in $(jq -r 'keys[]' "$ROOT/configs/data_contracts/paths.json"); do
  p=$(jq -r --arg k "$k" '.[$k].path // empty' "$ROOT/configs/data_contracts/paths.json")
  f="NO"
  [[ -n "$p" && -e "$p" ]] && f="YES"
  printf "%-24s | %-6s | %s\n" "$k" "$f" "$p"
done

# 也顯示 Windows 路徑（若在 WSL）
if command -v wslpath >/dev/null 2>&1; then
  echo -e "\n[WINDOWS PATH MIRROR]"
  for k in $(jq -r 'keys[]' "$ROOT/configs/data_contracts/paths.json"); do
    wp=$(jq -r --arg k "$k" '.[$k].win // empty' "$ROOT/configs/data_contracts/paths.json")
    [[ -z "$wp" ]] && continue
    printf "%-24s -> %s\n" "$k" "$wp"
  done
fi

echo -e "\nWrote: configs/data_contracts/paths.json  and  .env.local"
